require "ItemTweaker_Copy_CC";

-- TweakItem("", "DisplayCategory", "")

-- Zombie Cure

TweakItem("MC.Cura", "DisplayCategory", "Medical")
TweakItem("MC.AV1",  "DisplayCategory", "Medical")
TweakItem("MC.AV2",  "DisplayCategory", "Medical")
TweakItem("MC.AV3",  "DisplayCategory", "Medical")
TweakItem("MC.AV4",  "DisplayCategory", "Medical")
TweakItem("MC.AV5",  "DisplayCategory", "Medical")

-- Soul Filcher's Awesome Time 

TweakItem("filcher.HairDyeAuburn", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeAvocado", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeCherry", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeCyan", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeDarkBlue", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeDarkBrown", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeDarkTurquoise", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeDeepPurple", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeGrey", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeLightBlonde", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeLilac", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeLime", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeMagenta", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeOlive", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeOrange", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyePurple", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeSnowWhite", "DisplayCategory", "Appear")
TweakItem("filcher.HairDyeTurquoise", "DisplayCategory", "Appear")

TweakItem("filcher.NailGun", "DisplayCategory", "WepRange")
TweakItem("filcher.PoolballInSock", "DisplayCategory", "WepMelee")
TweakItem("filcher.Recorder", "DisplayCategory", "WepMelee")
TweakItem("filcher.UmbrellaPink", "DisplayCategory", "WepMelee")
TweakItem("filcher.ClosedUmbrellaPink", "DisplayCategory", "WepMelee")
TweakItem("filcher.WalkingCane", "DisplayCategory", "WepMelee")
TweakItem("filcher.WoodenCross", "DisplayCategory", "WepMelee")

TweakItem("filcher.JarWater", "DisplayCategory", "FoodB") 
TweakItem("filcher.PetrolCanWater", "DisplayCategory", "FoodB") 
TweakItem("filcher.PopCanWater", "DisplayCategory", "FoodB") 
TweakItem("filcher.Pop2CanWater", "DisplayCategory", "FoodB") 
TweakItem("filcher.Pop3CanWater", "DisplayCategory", "FoodB") 
TweakItem("filcher.RoastingPanWater", "DisplayCategory", "FoodB") 
TweakItem("filcher.TinCanWater", "DisplayCategory", "FoodB") 
TweakItem("filcher.WaterDishFull", "DisplayCategory", "FoodB") 
TweakItem("filcher.WaterGallon", "DisplayCategory", "FoodB") 
TweakItem("filcher.WaterGallonEmpty", "DisplayCategory", "Container") 

TweakItem("filcher.BottleWithGasPop", "DisplayCategory", "Craft")
TweakItem("filcher.BottleWithGasWater", "DisplayCategory", "Craft")
TweakItem("filcher.Flare", "DisplayCategory", "LightSource")
TweakItem("filcher.GasLantern", "DisplayCategory", "Tool")
TweakItem("filcher.GasLanternEmpty", "DisplayCategory", "Tool")
TweakItem("filcher.GasLanternLit", "DisplayCategory", "LightSource")
TweakItem("filcher.HeadTorch", "DisplayCategory", "LightSource")
TweakItem("filcher.TorchBranch", "DisplayCategory", "Tool")
TweakItem("filcher.TorchBranchLit", "DisplayCategory", "LightSource")
TweakItem("filcher.TorchChairLeg", "DisplayCategory", "Tool")
TweakItem("filcher.TorchChairLegLit", "DisplayCategory", "LightSource")
TweakItem("filcher.TorchPlank", "DisplayCategory", "Tool")
TweakItem("filcher.TorchPlankLit", "DisplayCategory", "LightSource")
TweakItem("filcher.TorchTableLeg", "DisplayCategory", "Tool")
TweakItem("filcher.TorchTableLegLit", "DisplayCategory", "LightSource")

TweakItem("filcher.SFAcorns", "DisplayCategory", "FoodN")
TweakItem("filcher.SFHickoryNut", "DisplayCategory", "FoodN")
TweakItem("filcher.SFHoney", "DisplayCategory", "FoodN")
TweakItem("filcher.SFPawpaw", "DisplayCategory", "FoodN")
TweakItem("filcher.SFPersimmon", "DisplayCategory", "FoodN")
TweakItem("filcher.SFPineNuts", "DisplayCategory", "FoodN")
TweakItem("filcher.SFPlum", "DisplayCategory", "FoodN")
TweakItem("filcher.SFRaspberry", "DisplayCategory", "FoodP")
TweakItem("filcher.SFTruffles", "DisplayCategory", "FoodP")
TweakItem("filcher.Cigarette", "DisplayCategory", "Drugs")
TweakItem("filcher.SFDeadCrow", "DisplayCategory", "FoodP")

TweakItem("filcher.BookMaintenance1", "DisplayCategory", "LitS")
TweakItem("filcher.BookMaintenance2", "DisplayCategory", "LitS")
TweakItem("filcher.BookMaintenance3", "DisplayCategory", "LitS")
TweakItem("filcher.BookMaintenance4", "DisplayCategory", "LitS")
TweakItem("filcher.BookMaintenance5", "DisplayCategory", "LitS")
TweakItem("filcher.BookMasonry1", "DisplayCategory", "LitS")
TweakItem("filcher.BookMasonry2", "DisplayCategory", "LitS")
TweakItem("filcher.BookMasonry3", "DisplayCategory", "LitS")
TweakItem("filcher.BookMasonry4", "DisplayCategory", "LitS")
TweakItem("filcher.BookMasonry5", "DisplayCategory", "LitS")
TweakItem("filcher.SFGuideCooking", "DisplayCategory", "LitR")
TweakItem("filcher.SFGuideEletronics", "DisplayCategory", "LitR")
TweakItem("filcher.SFGuideEngineering", "DisplayCategory", "LitR")
TweakItem("filcher.SFGuideFishing", "DisplayCategory", "LitR")
TweakItem("filcher.SFGuideMechanics", "DisplayCategory", "LitR")
TweakItem("filcher.SFGuideMetalworking", "DisplayCategory", "LitR")
TweakItem("filcher.SFGuideRadio", "DisplayCategory", "LitR")
TweakItem("filcher.SFGuideTrapping", "DisplayCategory", "LitR")
TweakItem("filcher.FarmingNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.FarmingNotes2", "DisplayCategory", "LitR")
TweakItem("filcher.FarmingNotes3", "DisplayCategory", "LitR")
TweakItem("filcher.FishingNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.FishingNotes2", "DisplayCategory", "LitR")
TweakItem("filcher.HuntingNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.HuntingNotes2", "DisplayCategory", "LitR")
TweakItem("filcher.HuntingNotes3", "DisplayCategory", "LitR")
TweakItem("filcher.HerbalistNotes", "DisplayCategory", "LitR")
TweakItem("filcher.MetalworkNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.MetalworkNotes2", "DisplayCategory", "LitR")
TweakItem("filcher.MetalworkNotes3", "DisplayCategory", "LitR")
TweakItem("filcher.MetalworkNotes4", "DisplayCategory", "LitR")
TweakItem("filcher.CookingNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.CookingNotes2", "DisplayCategory", "LitR")
TweakItem("filcher.SFCookingNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.ElectronicsNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.ElectronicsNotes2", "DisplayCategory", "LitR")
TweakItem("filcher.ElectronicsNotes3", "DisplayCategory", "LitR")
TweakItem("filcher.ElectronicsNotes4", "DisplayCategory", "LitR")
TweakItem("filcher.ElectronicsNotes5", "DisplayCategory", "LitR")
TweakItem("filcher.EngineerNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.EngineerNotes2", "DisplayCategory", "LitR")
TweakItem("filcher.EngineerNotes3", "DisplayCategory", "LitR")
TweakItem("filcher.EngineerNotes4", "DisplayCategory", "LitR")
TweakItem("filcher.EngineerNotes5", "DisplayCategory", "LitR")
TweakItem("filcher.MechanicNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.MechanicNotes2", "DisplayCategory", "LitR")
TweakItem("filcher.MechanicNotes3", "DisplayCategory", "LitR")
TweakItem("filcher.RadioNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.RadioNotes2", "DisplayCategory", "LitR")
TweakItem("filcher.RadioNotes3", "DisplayCategory", "LitR")
TweakItem("filcher.SmithingNotes1", "DisplayCategory", "LitR")
TweakItem("filcher.SmithingNotes2", "DisplayCategory", "LitR")
TweakItem("filcher.SmithingNotes3", "DisplayCategory", "LitR")
TweakItem("filcher.SmithingNotes4", "DisplayCategory", "LitR")
TweakItem("filcher.SmithingNotes5", "DisplayCategory", "LitR")

TweakItem("filcher.SFFarmMag2", "DisplayCategory", "LitR") 
TweakItem("filcher.SFFarmMag3", "DisplayCategory", "LitR") 
TweakItem("filcher.SFCookingMag1", "DisplayCategory", "LitR") 
TweakItem("filcher.SFCookingMag2", "DisplayCategory", "LitR") 
TweakItem("filcher.SFCookingMag3", "DisplayCategory", "LitR") 
TweakItem("filcher.SFBookFarm", "DisplayCategory", "LitR") 
TweakItem("filcher.SFCookingGuide", "DisplayCategory", "LitR") 
TweakItem("filcher.SFMasonMag", "DisplayCategory", "LitR") 
TweakItem("filcher.SFMetalworkMag5", "DisplayCategory", "LitR") 

-- Autotsar

TweakItem("Autotsar.AtTuningMagBus", "DisplayCategory", "LitR")
TweakItem("Autotsar.AtTuningMagJeep", "DisplayCategory", "LitR")
TweakItem("Autotsar.Bullbar2Blueprint", "DisplayCategory", "LitR")
TweakItem("Autotsar.Bullbar3Blueprint", "DisplayCategory", "LitR")
TweakItem("Autotsar.TrailerFirstTrunk", "DisplayCategory", "Tuning")
TweakItem("Autotsar.TrailerSecondTrunk", "DisplayCategory", "Tuning")

